export const customizedComponents = {
  accordion: [
    { title: "Default", type: "accordion", name: "default" },
    { title: "Outline", type: "accordion", name: "accordion-outline" },
    { title: "Box", type: "accordion", name: "accordion-box" },
    { title: "Contained", type: "accordion", name: "accordion-contained" },
    {
      title: "Box Contained",
      type: "accordion",
      name: "accordion-box-contained",
    },
    {
      title: "Tabs",
      type: "accordion",
      name: "accordion-tabs",
    },
    {
      title: "Highlight Active Item",
      type: "accordion",
      name: "accordion-highlight-active-item",
    },
    {
      title: "Multiple expanded at a time",
      type: "accordion",
      name: "accordion-multiple-open",
    },
    {
      title: "Expand Icon",
      type: "accordion",
      name: "accordion-expand-icon",
    },
    {
      title: "Icon",
      type: "accordion",
      name: "accordion-icon",
    },
    {
      title: "Media Content",
      type: "accordion",
      name: "accordion-media-content",
    },
    {
      title: "Disabled Item",
      type: "accordion",
      name: "accordion-item-disabled",
    },
    { title: "Controlled", type: "accordion", name: "accordion-controlled" },
  ],
  alert: [
    { title: "Primary", type: "alert", name: "default" },
    { title: "Destructive", type: "alert", name: "alert-destructive" },
    { title: "Success", type: "alert", name: "alert-success" },
    { title: "Warning", type: "alert", name: "alert-warning" },
    { title: "Info", type: "alert", name: "alert-info" },
    { title: "With background", type: "alert", name: "with-background" },
    { title: "Soft", type: "alert", name: "alert-soft" },
    { title: "Bootstrap", type: "alert", name: "alert-bootstrap" },
    { title: "Callout", type: "alert", name: "alert-callout" },
    { title: "With actions", type: "alert", name: "with-actions" },
  ],
  avatar: [
    { title: "Default", type: "avatar", name: "default" },
    {
      title: "Clickable",
      type: "avatar",
      name: "clickable",
    },
    {
      title: "Tooltip",
      type: "avatar",
      name: "tooltip",
    },
    {
      title: "With Text",
      type: "avatar",
      name: "with-text",
    },
    { title: "Hover Card", type: "avatar", name: "hover-card" },
    { title: "Size", type: "avatar", name: "size" },
    { title: "Color", type: "avatar", name: "color" },
    { title: "Shape", type: "avatar", name: "shape" },
    { title: "Fallback", type: "avatar", name: "fallback" },
    { title: "With Ring", type: "avatar", name: "with-ring" },
    { title: "Status", type: "avatar", name: "status" },
    { title: "Group", type: "avatar", name: "group" },
    { title: "Group max avatar", type: "avatar", name: "max-avatar-group" },
  ],
  badge: [
    { title: "Default", type: "badge", name: "default" },
    { title: "Secondary", type: "badge", name: "secondary" },
    { title: "Outline", type: "badge", name: "outline" },
    { title: "Destructive", type: "badge", name: "destructive" },
    { title: "Rounded", type: "badge", name: "rounded" },
    { title: "Gradient", type: "badge", name: "gradient" },
    { title: "Gradient Outline", type: "badge", name: "gradient-outline" },
    { title: "Soft", type: "badge", name: "soft" },
    { title: "Status", type: "badge", name: "status" },
    { title: "With image", type: "badge", name: "with-image" },
    { title: "With icon", type: "badge", name: "with-icon" },
    { title: "Clickable", type: "badge", name: "clickable" },
    { title: "Clickable link", type: "badge", name: "clickable-link" },
  ],
  breadcrumb: [
    { title: "Default", type: "breadcrumb", name: "default" },
    {
      title: "Slash Separator",
      type: "breadcrumb",
      name: "slash-separator",
    },
    {
      title: "Chevrons Separator",
      type: "breadcrumb",
      name: "chevrons-separator",
    },
    { title: "Dot Separator", type: "breadcrumb", name: "dot-separator" },
    {
      title: "With Icon",
      type: "breadcrumb",
      name: "with-icon",
    },
    {
      title: "With Icon 2",
      type: "breadcrumb",
      name: "with-icon-2",
    },
    {
      title: "With Icon and Label",
      type: "breadcrumb",
      name: "with-icon-and-label",
    },
    {
      title: "With Icon and Label 2",
      type: "breadcrumb",
      name: "with-icon-and-label-2",
    },
    {
      title: "With Background",
      type: "breadcrumb",
      name: "with-background",
    },
    {
      title: "Tab Active",
      type: "breadcrumb",
      name: "tab-active",
    },
    {
      title: "Tabs",
      type: "breadcrumb",
      name: "tabs",
    },
    {
      title: "Tabs Outline",
      type: "breadcrumb",
      name: "tabs-outline",
    },
    {
      title: "With Dropdown",
      type: "breadcrumb",
      name: "with-dropdown",
    },
    {
      title: "Collapsed",
      type: "breadcrumb",
      name: "collapsed",
    },
    {
      title: "Steps",
      type: "breadcrumb",
      name: "steps",
    },
  ],
  button: [
    { title: "Primary", type: "button", name: "primary-button" },
    { title: "Secondary", type: "button", name: "secondary-button" },
    { title: "Destructive", type: "button", name: "destructive-button" },
    { title: "Outline", type: "button", name: "outline-button" },
    { title: "Icon", type: "button", name: "icon-button" },
    { title: "Loading", type: "button", name: "loading-button" },
    { title: "Split Button", type: "button", name: "split-button" },
    { title: "Ghost", type: "button", name: "ghost-button" },
    { title: "Gradient", type: "button", name: "gradient-button" },
    { title: "Link", type: "button", name: "link-button" },
    { title: "Social", type: "button", name: "social-button" },
    { title: "Social Login", type: "button", name: "social-login-button" },
    { title: "Neon", type: "button", name: "neon-button" },
    { title: "Rounded", type: "button", name: "rounded-button" },
    { title: "Toggle", type: "button", name: "toggle-button" },
    { title: "Theme Toggle", type: "button", name: "theme-toggle" },
    { title: "Full Width", type: "button", name: "full-width-button" },
    { title: "Group", type: "button", name: "group-button" },
    { title: "Group 2", type: "button", name: "group-button-2" },
    { title: "Copy Button", type: "button", name: "copy-button" },
    { title: "With badge", type: "button", name: "with-badge" },
    { title: "With tooltip", type: "button", name: "with-tooltip" },
    { title: "With tap animation", type: "button", name: "with-tap-animation" },
  ],
  card: [
    { title: "Default", type: "card", name: "default" },
    { title: "With background", type: "card", name: "with-background" },
    { title: "Sign Up", type: "card", name: "create-account" },
    { title: "Banner", type: "card", name: "card-banner" },
    { title: "Pricing", type: "card", name: "card-pricing" },
    { title: "Post", type: "card", name: "card-post" },
    { title: "Product", type: "card", name: "product-card" },
    { title: "Testimonial", type: "card", name: "testimonial-card" },
  ],
  carousel: [
    { title: "Default", type: "carousel", name: "default" },
    { title: "Multiple slides", type: "carousel", name: "multiple-slides" },
    { title: "Vertical", type: "carousel", name: "vertical" },
    { title: "Slide Status", type: "carousel", name: "slide-status" },
    { title: "Slide Status 2", type: "carousel", name: "slide-status-2" },
    { title: "Pagination", type: "carousel", name: "pagination" },
    { title: "Footer", type: "carousel", name: "footer" },
    { title: "Progress", type: "carousel", name: "progress" },
    { title: "Thumbs", type: "carousel", name: "thumbs" },
    { title: "Opacity", type: "carousel", name: "opacity" },
    { title: "Scale", type: "carousel", name: "scale" },
  ],
  checkbox: [
    { title: "With Text", type: "checkbox", name: "with-text" },
    { title: "Disabled", type: "checkbox", name: "disabled-checkbox" },
    { title: "Indeterminate", type: "checkbox", name: "indeterminate" },
    { title: "Horizontal Group", type: "checkbox", name: "horizontal-group" },
    { title: "Vertical Group", type: "checkbox", name: "vertical-group" },
    { title: "Controlled", type: "checkbox", name: "controlled" },
    { title: "Colors", type: "checkbox", name: "colors" },
    { title: "Sizes", type: "checkbox", name: "sizes" },
    { title: "Icon", type: "checkbox", name: "icon" },
    {
      title: "Multi Color Picker",
      type: "checkbox",
      name: "multi-color-picker",
    },
    { title: "Card", type: "checkbox", name: "card-1" },
  ],
  input: [
    { title: "Default", type: "input", name: "default-input" },
    { title: "Ring", type: "input", name: "ring-input" },
    { title: "Filled", type: "input", name: "filled-input" },
    { title: "Disabled", type: "input", name: "disabled-input" },
    { title: "With label", type: "input", name: "with-label" },
    { title: "With button", type: "input", name: "with-button" },
    { title: "With adornments", type: "input", name: "with-adornment" },
    { title: "With helper text", type: "input", name: "with-helper-text" },
    { title: "With error message", type: "input", name: "with-error-message" },
    { title: "File input", type: "input", name: "file-input" },
    { title: "Dropzone", type: "input", name: "dropzone" },
  ],
  "input-otp": [
    { title: "Default", type: "input-otp", name: "default" },
    {
      title: "Without Separator",
      type: "input-otp",
      name: "without-separator",
    },
    { title: "Separated", type: "input-otp", name: "separated" },
    {
      title: "Separated 2",
      type: "input-otp",
      name: "separated-2",
    },
    { title: "Secondary", type: "input-otp", name: "secondary" },
    { title: "Custom Separator", type: "input-otp", name: "custom-separator" },
    { title: "Inner Shadow", type: "input-otp", name: "inner-shadow" },
  ],
  pagination: [
    { title: "Default", type: "pagination", name: "default" },
    {
      title: "Primary Button",
      type: "pagination",
      name: "primary-button",
    },
    {
      title: "Secondary Button",
      type: "pagination",
      name: "secondary-button",
    },
    { title: "Rounded Button", type: "pagination", name: "rounded-button" },
    {
      title: "With Icon",
      type: "pagination",
      name: "icon",
    },
    {
      title: "First and Last Page Buttons",
      type: "pagination",
      name: "first-last-page",
    },
    {
      title: "Bordered",
      type: "pagination",
      name: "bordered",
    },
    {
      title: "Tabs",
      type: "pagination",
      name: "tabs",
    },
    {
      title: "Tabs Secondary",
      type: "pagination",
      name: "tabs-secondary",
    },
    {
      title: "With Icon and Label",
      type: "pagination",
      name: "icon-and-label",
    },
    {
      title: "Numberless Pagination",
      type: "pagination",
      name: "numberless",
    },
    {
      title: "Numberless with Text",
      type: "pagination",
      name: "numberless-with-text",
    },
    { title: "With ellipsis", type: "pagination", name: "ellipsis" },
    {
      title: "Table Pagination",
      type: "pagination",
      name: "table-pagination",
    },
  ],
  progress: [
    { title: "Default", type: "progress", name: "default" },
    { title: "Linear with label", type: "progress", name: "linear-with-label" },
    { title: "Linear color", type: "progress", name: "linear-color" },
    { title: "Rounded progress indicator", type: "progress", name: "rounded" },
    { title: "Gradient", type: "progress", name: "gradient" },
    { title: "Animation", type: "progress", name: "animation" },
    { title: "Circular", type: "progress", name: "circular" },
    {
      title: "Circular with label",
      type: "progress",
      name: "circular-with-label",
    },
    {
      title: "Circular with custom label",
      type: "progress",
      name: "circular-with-custom-label",
    },
    { title: "Circular color", type: "progress", name: "circular-color" },
    {
      title: "Circular progress shape",
      type: "progress",
      name: "circular-progress-shape",
    },
    {
      title: "Circular stroke width",
      type: "progress",
      name: "circular-stroke-width",
    },
  ],
  "radio-group": [
    { title: "Default", type: "radio-group", name: "default" },
    { title: "Orientation", type: "radio-group", name: "orientation" },
    { title: "Disabled", type: "radio-group", name: "disabled" },
    { title: "Color", type: "radio-group", name: "color" },
    { title: "Size", type: "radio-group", name: "size" },
    { title: "Variant", type: "radio-group", name: "variant" },
    { title: "Cards 1", type: "radio-group", name: "cards-1" },
    { title: "Cards 2", type: "radio-group", name: "cards-2" },
    { title: "Cards 3", type: "radio-group", name: "cards-3" },
  ],
  select: [
    { title: "Default", type: "select", name: "default" },
    { title: "Color", type: "select", name: "color" },
    { title: "Ghost", type: "select", name: "ghost" },
    {
      title: "Custom dropdown icon",
      type: "select",
      name: "custom-dropdown-icon",
    },
    { title: "Shape", type: "select", name: "shape" },
    { title: "With an icon", type: "select", name: "with-icon" },
    { title: "Theme Selector", type: "select", name: "theme-selector" },
    {
      title: "Select menu position",
      type: "select",
      name: "select-menu-position",
    },
    { title: "Scrollable", type: "select", name: "scrollable" },
    { title: "Controlled", type: "select", name: "controlled" },
    { title: "With auto complete", type: "select", name: "with-auto-complete" },
  ],
  separator: [
    { title: "Default", type: "separator", name: "default" },
    {
      title: "Horizontal separator with label",
      type: "separator",
      name: "with-label-horizontal",
    },
    {
      title: "Horizontal separator with chip",
      type: "separator",
      name: "with-chip-horizontal",
    },
    { title: "Dashed", type: "separator", name: "separator-dashed" },
    { title: "Vertical", type: "separator", name: "separator-vertical" },
    {
      title: "Vertical with chip",
      type: "separator",
      name: "with-chip-vertical",
    },
  ],
  slider: [
    { title: "Default", type: "slider", name: "default" },
    { title: "Disabled", type: "slider", name: "disabled" },
    { title: "Size", type: "slider", name: "size" },
    { title: "Color", type: "slider", name: "color" },
    { title: "Shape", type: "slider", name: "shape" },
    { title: "With label", type: "slider", name: "with-label" },
    { title: "Thumb Icon", type: "slider", name: "thumb-icon" },
    { title: "Audio Slider", type: "slider", name: "audio-slider" },
    { title: "Marks", type: "slider", name: "marks" },
    { title: "Sticky label", type: "slider", name: "sticky-label" },
    {
      title: "Sticky Label on Hover",
      type: "slider",
      name: "sticky-label-hover",
    },
    {
      title: "Sticky Label with Arrow",
      type: "slider",
      name: "sticky-label-arrow",
    },
    { title: "Vertical", type: "slider", name: "vertical" },
    { title: "Range", type: "slider", name: "range" },
    { title: "Multiple Thumbs", type: "slider", name: "multiple-thumbs" },
  ],
  spinner: [
    { title: "Default", type: "spinner", name: "default" },
    { title: "Circle", type: "spinner", name: "spinner-circle" },
    { title: "Pinwheel", type: "spinner", name: "spinner-pinwheel" },
    { title: "Colors", type: "spinner", name: "spinner-colors" },
    { title: "Sizes", type: "spinner", name: "spinner-sizes" },
    {
      title: "Swirling Effect",
      type: "spinner",
      name: "swirling-effect",
      credit: {
        label: "fffuel",
        link: "https://www.fffuel.co/svg-spinner/",
      },
    },
  ],
  switch: [
    { title: "Default", type: "switch", name: "default" },
    { title: "With label", type: "switch", name: "with-label" },
    { title: "Disabled", type: "switch", name: "disabled" },
    { title: "Colors", type: "switch", name: "colors" },
    { title: "Sizes", type: "switch", name: "sizes" },
    { title: "Controlled", type: "switch", name: "controlled" },
    { title: "Customization", type: "switch", name: "customization" },
  ],
  table: [
    { title: "Default", type: "table", name: "default" },
    { title: "Bordered", type: "table", name: "bordered" },
    { title: "Striped rows", type: "table", name: "striped-rows" },
    { title: "Rounded corners", type: "table", name: "rounded-corners" },
    { title: "With pagination", type: "table", name: "with-pagination" },
    { title: "Sticky header", type: "table", name: "sticky-header" },
    { title: "Sticky columns", type: "table", name: "sticky-columns" },
    { title: "Overflow scroll", type: "table", name: "overflow-scroll" },
    { title: "Data Table", type: "table", name: "data-table" },
    { title: "Data Table Density", type: "table", name: "data-table-density" },
    { title: "Columns Visibility", type: "table", name: "columns-visibility" },
  ],
  tabs: [
    { title: "Default", type: "tabs", name: "default" },
    { title: "Underlined", type: "tabs", name: "underlined-tabs" },
    { title: "Separated", type: "tabs", name: "separated-tabs" },
    { title: "Bordered", type: "tabs", name: "tabs-bordered" },
    { title: "Box", type: "tabs", name: "tabs-box" },
    { title: "Bootstrap", type: "tabs", name: "tabs-bootstrap" },
    { title: "Icon", type: "tabs", name: "tabs-icon" },
    {
      title: "Mobile Navigation",
      type: "tabs",
      name: "tabs-mobile-navigation",
    },
    { title: "With badge", type: "tabs", name: "tabs-with-badge" },
    { title: "Sharp", type: "tabs", name: "tabs-sharp" },
    { title: "Shadow", type: "tabs", name: "tabs-shadow" },
    { title: "Skewed", type: "tabs", name: "tabs-skewed" },
    { title: "Vertical", type: "tabs", name: "vertical-tabs" },
    {
      title: "Vertical Left Bordered",
      type: "tabs",
      name: "vertical-left-bordered",
    },
    { title: "Vertical Separated", type: "tabs", name: "vertical-separated" },
    { title: "Vertical Sharp", type: "tabs", name: "vertical-sharp" },
    { title: "Vertical Bordered", type: "tabs", name: "vertical-bordered" },
    { title: "Animated Content", type: "tabs", name: "animated-tabs" },
  ],
  textarea: [
    { title: "Default", type: "textarea", name: "default" },
    {
      title: "With background",
      type: "textarea",
      name: "with-background-color",
    },
    { title: "Disabled", type: "textarea", name: "disabled" },
    { title: "With label", type: "textarea", name: "with-label" },
    { title: "Rows", type: "textarea", name: "rows" },
    { title: "With helper text", type: "textarea", name: "with-helper-text" },
    { title: "Controlled", type: "textarea", name: "controlled" },
  ],
  tooltip: [
    { title: "Default", type: "tooltip", name: "default" },
    { title: "With arrow", type: "tooltip", name: "with-arrow" },
    { title: "Directions", type: "tooltip", name: "tooltip-directions" },
    {
      title: "Disable Hoverable Content",
      type: "tooltip",
      name: "with-disabled-hoverable-content",
      description:
        "Prevents TooltipContent from remaining open when hovering. Disabling this has accessibility consequences.",
    },
    { title: "With delay", type: "tooltip", name: "tooltip-with-delay" },
    {
      title: "With skip delay",
      type: "tooltip",
      name: "tooltip-with-skip-delay-duration",
      description:
        "How much time a user has to enter another trigger without incurring a delay again.",
    },
    {
      title: "Portal",
      type: "tooltip",
      name: "tooltip-portal",
      description: "When used, portals the content part into the body.",
    },
  ],
};
